author: Wojciech Danilo
bug-reports: https://github.com/wdanilo/poly-control/issues
category: Data
copyright: Copyright (C) 2015 Wojciech Danilo
default-extensions: [ConstraintKinds, DataKinds, DefaultSignatures, DeriveDataTypeable,
  DeriveFoldable, DeriveFunctor, DeriveGeneric, DeriveTraversable, DoAndIfThenElse,
  EmptyDataDecls, FlexibleContexts, FlexibleInstances, GeneralizedNewtypeDeriving,
  InstanceSigs, LambdaCase, MultiParamTypeClasses, OverloadedStrings, StandaloneDeriving,
  TemplateHaskell, TupleSections, TypeOperators, ViewPatterns, TypeFamilies]
dependencies: [base >=4.6 && <4.10]
ghc-options: [-Wall, -O2]
homepage: https://github.com/wdanilo/poly-control
library:
  exposed-modules: [Control.Applicative.Poly, Control.Monad.Poly, Control.Monad.Shuffle,
    Control.Poly]
  source-dirs: src
license: Apache-2.0
maintainer: Wojciech Danilo <wojciech.danilo@gmail.com>
name: poly-control
stability: experimental
synopsis: This package provides abstraction for polymorphic controls, like PolyMonads
  or PolyApplicatives.
version: 1.1
